project_id = "paymvttrbrwmcybbhipe"

[functions.generate-image]
verify_jwt = true

[functions.fetch-url-context]
verify_jwt = true

[functions.generate-html-component]
verify_jwt = true

[functions.upscale-image]
verify_jwt = true

[functions.send-password-change-notification]
verify_jwt = true

[functions.search-unsplash]
verify_jwt = true

[functions.generate-campaign-strategy]
verify_jwt = true
