// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paymvttrbrwmcybbhipe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBheW12dHRyYnJ3bWN5YmJoaXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzQzNTAsImV4cCI6MjA3MTgxMDM1MH0.6tnGLBgsfdr2dxaTThvvpmHKy-FHZ9KvQbDIyDYrTw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});